# Generated by Django 4.0.6 on 2022-07-31 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome aluno:', max_length=150)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Informe a disciplina', max_length=100, verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField(help_text='Por favor, informe o enunciado')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.TextField(choices=[('fund_1', '1ª série ensino fundamental'), ('fund_2', '2ª série ensino fundamental'), ('fund_3', '3ª série ensino fundamental'), ('fund_4', '4ª série ensino fundamental'), ('fund_5', '5ª série ensino fundamental'), ('fund_6', '6ª série ensino fundamental'), ('fund_7', '7ª série ensino fundamental'), ('fund_8', '8ª série ensino fundamental'), ('fund_9', '9ª série ensino fundamental'), ('medio_1', '1ª série ensino médio'), ('medio_2', '2ª série ensino médio'), ('medio_3', '3ª série ensino médio')], default=None, help_text='Por favor, informe a série')),
            ],
            options={
                'verbose_name': 'Serie',
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField(choices=[('a', 'Alternativa A'), ('b', 'Alternativa B'), ('c', 'Alternativa C'), ('d', 'Alternativa D')], default=None, verbose_name='Alternativa correta:')),
                ('is_correta', models.BooleanField(default=None)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.aluno')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.pergunta')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
            },
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimestre', models.TextField(choices=[('1', '1º bimestre'), ('2', '2º bimestre'), ('3', '3º bimestre'), ('4', '4º bimestre')], default=None, help_text='Por favor, informe o bimestre')),
                ('is_recuperacao', models.BooleanField(default=False)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.disciplina')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paginas.serie')),
            ],
            options={
                'verbose_name': 'Questionario',
                'verbose_name_plural': 'Questionarios',
            },
        ),
        migrations.AddField(
            model_name='pergunta',
            name='questionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.questionario'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paginas.disciplina'),
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativa_a', models.TextField(help_text='Por favor, informe a alternativa', verbose_name='Alternativa A')),
                ('alternativa_b', models.TextField(help_text='Por favor, informe a alternativa', verbose_name='Alternativa B')),
                ('alternativa_c', models.TextField(help_text='Por favor, informe a alternativa', verbose_name='Alternativa C')),
                ('alternativa_d', models.TextField(help_text='Por favor, informe a alternativa', verbose_name='Alternativa D')),
                ('alternativa_correta', models.TextField(choices=[(None, ''), ('a', 'Resposta A'), ('b', 'Resposta B'), ('c', 'Resposta C'), ('d', 'Resposta D')], default=None, verbose_name='Alternativa correta:')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.pergunta')),
            ],
            options={
                'verbose_name': 'Alternativa',
                'verbose_name_plural': 'Alternativas',
            },
        ),
    ]
