# Generated by Django 4.0.6 on 2022-07-31 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paginas.serie'),
        ),
    ]
