# Generated by Django 4.0.6 on 2022-07-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_alter_aluno_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='serie',
            field=models.TextField(default=None, help_text='Por favor, informe a série'),
        ),
    ]
