# Generated by Django 4.0.6 on 2022-07-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_alter_serie_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='serie',
            field=models.CharField(default=None, help_text='Por favor, informe a série', max_length=100),
        ),
    ]
